-- KumariCinema Database Setup Script
-- Run in Oracle SQL Developer as user Salina

-- DROP existing tables (order matters for FK constraints)
BEGIN
  FOR t IN (SELECT table_name FROM user_tables WHERE table_name IN (
    'TICKETSHOW','TICKET','SHOWHALL','SHOW_TABLE','HALLTHEATER','HALL','THEATERMOVIEMAP','THEATER','MOVIEUSER','MOVIE','USERS'
  )) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
  END LOOP;
END;
/

-- USERS Table
CREATE TABLE USERS (
    UserId      NUMBER PRIMARY KEY,
    Username    VARCHAR2(100) NOT NULL,
    UserEmail   VARCHAR2(150) UNIQUE NOT NULL,
    Password    VARCHAR2(100) NOT NULL,
    Address     VARCHAR2(200)
);

-- MOVIE Table
CREATE TABLE MOVIE (
    MovieId     NUMBER PRIMARY KEY,
    MovieTitle  VARCHAR2(200) NOT NULL,
    Duration    NUMBER(3) NOT NULL,
    Language    VARCHAR2(50) NOT NULL,
    Genre       VARCHAR2(100) NOT NULL,
    ReleaseDate DATE NOT NULL
);

-- MOVIEUSER (junction)
CREATE TABLE MOVIEUSER (
    MovieId NUMBER REFERENCES MOVIE(MovieId),
    UserId  NUMBER REFERENCES USERS(UserId),
    PRIMARY KEY (MovieId, UserId)
);

-- THEATER Table
CREATE TABLE THEATER (
    TheaterId   NUMBER PRIMARY KEY,
    TheaterName VARCHAR2(200) NOT NULL,
    TheaterCity VARCHAR2(100) NOT NULL,
    TheatreType VARCHAR2(100) NOT NULL
);

-- THEATERMOVIEMAP (junction)
CREATE TABLE THEATERMOVIEMAP (
    TheaterId NUMBER REFERENCES THEATER(TheaterId),
    UserId    NUMBER REFERENCES USERS(UserId),
    MovieId   NUMBER REFERENCES MOVIE(MovieId),
    PRIMARY KEY (TheaterId, UserId, MovieId)
);

-- HALL Table
CREATE TABLE HALL (
    HallId       NUMBER PRIMARY KEY,
    HallCapacity NUMBER NOT NULL,
    HallType     VARCHAR2(100) NOT NULL,
    FloorNo      NUMBER NOT NULL,
    TotalSeats   NUMBER NOT NULL
);

-- HALLTHEATER (junction)
CREATE TABLE HALLTHEATER (
    HallId    NUMBER REFERENCES HALL(HallId),
    UserId    NUMBER REFERENCES USERS(UserId),
    MovieId   NUMBER REFERENCES MOVIE(MovieId),
    TheaterId NUMBER REFERENCES THEATER(TheaterId),
    PRIMARY KEY (HallId, UserId, MovieId, TheaterId)
);

-- SHOW_TABLE Table
CREATE TABLE SHOW_TABLE (
    ShowId     NUMBER PRIMARY KEY,
    ShowName   VARCHAR2(200) NOT NULL,
    ShowDate   DATE NOT NULL,
    ShowType   VARCHAR2(100) NOT NULL,
    ShowStatus VARCHAR2(50) DEFAULT 'Active' NOT NULL
);

-- SHOWHALL (junction)
CREATE TABLE SHOWHALL (
    ShowId    NUMBER REFERENCES SHOW_TABLE(ShowId),
    UserId    NUMBER REFERENCES USERS(UserId),
    MovieId   NUMBER REFERENCES MOVIE(MovieId),
    TheaterId NUMBER REFERENCES THEATER(TheaterId),
    HallId    NUMBER REFERENCES HALL(HallId),
    PRIMARY KEY (ShowId, UserId, MovieId, TheaterId, HallId)
);

-- TICKET Table
CREATE TABLE TICKET (
    TicketId      NUMBER PRIMARY KEY,
    TicketPrice   NUMBER(10,2),
    TicketDate    DATE,
    TicketStatus  VARCHAR2(50) DEFAULT 'Booked',
    PaymentStatus VARCHAR2(50) DEFAULT 'Pending'
);

-- TICKETSHOW (junction)
CREATE TABLE TICKETSHOW (
    TicketId  NUMBER REFERENCES TICKET(TicketId),
    UserId    NUMBER REFERENCES USERS(UserId),
    MovieId   NUMBER REFERENCES MOVIE(MovieId),
    TheaterId NUMBER REFERENCES THEATER(TheaterId),
    HallId    NUMBER REFERENCES HALL(HallId),
    ShowId    NUMBER REFERENCES SHOW_TABLE(ShowId),
    PRIMARY KEY (TicketId, UserId, MovieId, TheaterId, HallId, ShowId)
);

-- Sequences
CREATE SEQUENCE SEQ_USER  START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MOVIE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_THEATER START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_HALL  START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SHOW  START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TICKET START WITH 1 INCREMENT BY 1;

-- Sample Data: USERS
INSERT INTO USERS VALUES (SEQ_USER.NEXTVAL,'Pratibha Gurung','pratibha@email.com','pass123','Pokhara');
INSERT INTO USERS VALUES (SEQ_USER.NEXTVAL,'Ram Shrestha','ram@email.com','pass123','Kathmandu');
INSERT INTO USERS VALUES (SEQ_USER.NEXTVAL,'Sita Paudel','sita@email.com','pass123','Lalitpur');
INSERT INTO USERS VALUES (SEQ_USER.NEXTVAL,'Hari Thapa','hari@email.com','pass123','Birgunj');
INSERT INTO USERS VALUES (SEQ_USER.NEXTVAL,'Gita Karki','gita@email.com','pass123','Biratnagar');

-- Sample Data: MOVIE
INSERT INTO MOVIE VALUES (SEQ_MOVIE.NEXTVAL,'Avatar: Fire and Ash',180,'English','Fiction',TO_DATE('2025-12-19','YYYY-MM-DD'));
INSERT INTO MOVIE VALUES (SEQ_MOVIE.NEXTVAL,'Shershaah',135,'Hindi','Action',TO_DATE('2025-11-05','YYYY-MM-DD'));
INSERT INTO MOVIE VALUES (SEQ_MOVIE.NEXTVAL,'Laapataa Ladies',120,'Hindi','Drama',TO_DATE('2025-10-01','YYYY-MM-DD'));
INSERT INTO MOVIE VALUES (SEQ_MOVIE.NEXTVAL,'Inception',148,'English','Sci-Fi',TO_DATE('2025-09-15','YYYY-MM-DD'));
INSERT INTO MOVIE VALUES (SEQ_MOVIE.NEXTVAL,'Interstellar',169,'English','Sci-Fi',TO_DATE('2025-08-20','YYYY-MM-DD'));

-- Sample Data: THEATER
INSERT INTO THEATER VALUES (SEQ_THEATER.NEXTVAL,'KumariCinemas Pokhara Cineplex','Pokhara','Multiplex');
INSERT INTO THEATER VALUES (SEQ_THEATER.NEXTVAL,'KumariCinemas Labim Mall','Kathmandu','Multiplex');
INSERT INTO THEATER VALUES (SEQ_THEATER.NEXTVAL,'KumariCinemas Biratnagar','Biratnagar','Single Screen');
INSERT INTO THEATER VALUES (SEQ_THEATER.NEXTVAL,'KumariCinemas Lalitpur','Lalitpur','Multiplex');
INSERT INTO THEATER VALUES (SEQ_THEATER.NEXTVAL,'KumariCinemas Birgunj','Birgunj','Single Screen');

-- Sample Data: HALL
INSERT INTO HALL VALUES (SEQ_HALL.NEXTVAL,326,'Standard',1,326);
INSERT INTO HALL VALUES (SEQ_HALL.NEXTVAL,231,'Premium',2,231);
INSERT INTO HALL VALUES (SEQ_HALL.NEXTVAL,182,'Standard',1,182);
INSERT INTO HALL VALUES (SEQ_HALL.NEXTVAL,180,'IMAX',3,180);
INSERT INTO HALL VALUES (SEQ_HALL.NEXTVAL,200,'Standard',1,200);

-- Sample Data: SHOW_TABLE
INSERT INTO SHOW_TABLE VALUES (SEQ_SHOW.NEXTVAL,'Morning Show',TO_DATE('2025-12-21','YYYY-MM-DD'),'Morning','Active');
INSERT INTO SHOW_TABLE VALUES (SEQ_SHOW.NEXTVAL,'Day Show',TO_DATE('2025-12-21','YYYY-MM-DD'),'Day','Active');
INSERT INTO SHOW_TABLE VALUES (SEQ_SHOW.NEXTVAL,'Evening Show',TO_DATE('2025-12-21','YYYY-MM-DD'),'Evening','Active');
INSERT INTO SHOW_TABLE VALUES (SEQ_SHOW.NEXTVAL,'Morning Show',TO_DATE('2025-12-22','YYYY-MM-DD'),'Morning','Active');
INSERT INTO SHOW_TABLE VALUES (SEQ_SHOW.NEXTVAL,'Night Show',TO_DATE('2025-12-22','YYYY-MM-DD'),'Night','Active');
INSERT INTO SHOW_TABLE VALUES (SEQ_SHOW.NEXTVAL,'Day Show',TO_DATE('2025-12-23','YYYY-MM-DD'),'Day','Active');
INSERT INTO SHOW_TABLE VALUES (SEQ_SHOW.NEXTVAL,'Evening Show',TO_DATE('2025-12-23','YYYY-MM-DD'),'Evening','Active');
INSERT INTO SHOW_TABLE VALUES (SEQ_SHOW.NEXTVAL,'Morning Show',TO_DATE('2025-12-24','YYYY-MM-DD'),'Morning','Active');
INSERT INTO SHOW_TABLE VALUES (SEQ_SHOW.NEXTVAL,'Day Show',TO_DATE('2025-12-24','YYYY-MM-DD'),'Day','Active');
INSERT INTO SHOW_TABLE VALUES (SEQ_SHOW.NEXTVAL,'Night Show',TO_DATE('2025-12-25','YYYY-MM-DD'),'Night','Active');

-- Sample Data: TICKET
INSERT INTO TICKET VALUES (SEQ_TICKET.NEXTVAL,390,TO_DATE('2025-12-21','YYYY-MM-DD'),'Paid','Completed');
INSERT INTO TICKET VALUES (SEQ_TICKET.NEXTVAL,420,TO_DATE('2025-12-21','YYYY-MM-DD'),'Paid','Completed');
INSERT INTO TICKET VALUES (SEQ_TICKET.NEXTVAL,200,TO_DATE('2025-12-21','YYYY-MM-DD'),'Booked','Pending');
INSERT INTO TICKET VALUES (SEQ_TICKET.NEXTVAL,390,TO_DATE('2025-12-22','YYYY-MM-DD'),'Cancelled','Failed');
INSERT INTO TICKET VALUES (SEQ_TICKET.NEXTVAL,420,TO_DATE('2025-12-22','YYYY-MM-DD'),'Paid','Completed');
INSERT INTO TICKET VALUES (SEQ_TICKET.NEXTVAL,200,TO_DATE('2025-12-23','YYYY-MM-DD'),'Paid','Completed');
INSERT INTO TICKET VALUES (SEQ_TICKET.NEXTVAL,390,TO_DATE('2025-12-23','YYYY-MM-DD'),'Booked','Pending');
INSERT INTO TICKET VALUES (SEQ_TICKET.NEXTVAL,420,TO_DATE('2025-12-24','YYYY-MM-DD'),'Paid','Completed');
INSERT INTO TICKET VALUES (SEQ_TICKET.NEXTVAL,200,TO_DATE('2025-12-24','YYYY-MM-DD'),'Paid','Completed');
INSERT INTO TICKET VALUES (SEQ_TICKET.NEXTVAL,390,TO_DATE('2025-12-25','YYYY-MM-DD'),'Cancelled','Failed');

-- Junction: MOVIEUSER
INSERT INTO MOVIEUSER VALUES(1,1); INSERT INTO MOVIEUSER VALUES(2,2);
INSERT INTO MOVIEUSER VALUES(3,3); INSERT INTO MOVIEUSER VALUES(4,4);
INSERT INTO MOVIEUSER VALUES(5,5);

-- Junction: THEATERMOVIEMAP
INSERT INTO THEATERMOVIEMAP VALUES(1,1,1); INSERT INTO THEATERMOVIEMAP VALUES(2,2,1);
INSERT INTO THEATERMOVIEMAP VALUES(3,3,2); INSERT INTO THEATERMOVIEMAP VALUES(4,4,3);
INSERT INTO THEATERMOVIEMAP VALUES(5,5,4);

-- Junction: HALLTHEATER
INSERT INTO HALLTHEATER VALUES(1,1,1,1); INSERT INTO HALLTHEATER VALUES(2,2,1,2);
INSERT INTO HALLTHEATER VALUES(3,3,2,3); INSERT INTO HALLTHEATER VALUES(4,4,3,4);
INSERT INTO HALLTHEATER VALUES(5,5,4,5);

-- Junction: SHOWHALL
INSERT INTO SHOWHALL VALUES(1,1,1,1,1); INSERT INTO SHOWHALL VALUES(2,2,1,2,2);
INSERT INTO SHOWHALL VALUES(3,3,2,3,3); INSERT INTO SHOWHALL VALUES(4,4,3,4,4);
INSERT INTO SHOWHALL VALUES(5,5,4,5,5);

-- Junction: TICKETSHOW
INSERT INTO TICKETSHOW VALUES(1,1,1,1,1,1); INSERT INTO TICKETSHOW VALUES(2,2,1,2,2,2);
INSERT INTO TICKETSHOW VALUES(3,3,2,3,3,3); INSERT INTO TICKETSHOW VALUES(4,4,3,4,4,4);
INSERT INTO TICKETSHOW VALUES(5,5,4,5,5,5); INSERT INTO TICKETSHOW VALUES(6,1,2,1,3,6);
INSERT INTO TICKETSHOW VALUES(7,2,3,2,4,7); INSERT INTO TICKETSHOW VALUES(8,3,4,3,5,8);
INSERT INTO TICKETSHOW VALUES(9,4,5,4,1,9); INSERT INTO TICKETSHOW VALUES(10,5,1,5,2,10);

COMMIT;
